In [1]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import io
from google.colab import files
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import keras
from keras.models import Sequential
from keras.layers import Dense #to add layers

from sklearn.metrics import confusion_matrix

Using TensorFlow backend.

**1: Read the dataset**

In [3]:
# load dataset from local drive
uploaded = files.upload()

df = pd.read_csv(io.BytesIO(uploaded['bank (1).csv']))
df.describe(include='all').T

Saving bank (1).csv to bank (1) (1).csv

                 count unique     top  ...          50%          75%          max
RowNumber        10000    NaN     NaN  ...       5000.5      7500.25        10000
CustomerId       10000    NaN     NaN  ...  1.56907e+07  1.57532e+07  1.58157e+07
Surname          10000   2932   Smith  ...          NaN          NaN          NaN
CreditScore      10000    NaN     NaN  ...          652          718          850
Geography        10000      3  France  ...          NaN          NaN          NaN
Gender           10000      2    Male  ...          NaN          NaN          NaN
Age              10000    NaN     NaN  ...           37           44           92
Tenure           10000    NaN     NaN  ...            5            7           10
Balance          10000    NaN     NaN  ...      97198.5       127644       250898
NumOfProducts    10000    NaN     NaN  ...            1            2            4
HasCrCard        10000    NaN     NaN  ...            1            1            1
IsActiveMember   10000    NaN     NaN  ...            1            1            1
EstimatedSalary  10000    NaN     NaN  ...       100194       149388       199992
Exited           10000    NaN     NaN  ...            0            0            1

[14 rows x 11 columns]

**1.2: Drop the columns which are unique for all users like IDs (5 points)**

In [4]:
# Drop columns - RowNumber, CustomerId, Surname
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

**1.3: Distinguish the feature and target set (5 points)**

In [0]:
#include relevant columns within x and y
x = df.iloc[:, 0:10]
y = df.iloc[:, 10]

**Extras: Additiona preprocessing steps**

In [6]:
#deal with categorical data --> encode them
labelencoder_x = LabelEncoder()
x.iloc[:, 1] = labelencoder_x.fit_transform(x.iloc[:, 1]) #applying on Geography
x.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [7]:
#apply encoder on Gender as well
labelencoder_x_2 = LabelEncoder()
x.iloc[:, 2] = labelencoder_x_2.fit_transform(x.iloc[:, 2]) #applying on Gender
x.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [8]:
#One hot encoding.
encoded = pd.DataFrame(to_categorical(x.iloc[:, 1]))
#no need to encode Gender, as there are only two categories

x = pd.concat([encoded, x], axis = 1)

#Dropping the existing "geography" category, and one of the onehotcoded columns.
x = x.drop(['Geography', 0], axis = 1)
x.head()

     1    2  CreditScore  ...  HasCrCard  IsActiveMember  EstimatedSalary
0  0.0  0.0          619  ...          1               1        101348.88
1  0.0  1.0          608  ...          0               1        112542.58
2  0.0  0.0          502  ...          1               0        113931.57
3  0.0  0.0          699  ...          0               0         93826.63
4  0.0  1.0          850  ...          1               1         79084.10

[5 rows x 11 columns]

**1.4: Divide the data set into Train and test sets**

In [0]:
#train and test set split, and feature scaling
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

**1.5: Normalize the train and test data (5 points)**

In [0]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**1.6: Initialize & build the model (10 points)**

In [11]:
# Build the model using Keras

classifier = Sequential()
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
#init --> initialize weights according to uniform distribution
#input_dim is required for the first hidden layer, as it is the first starting point. --> number of nodes.
#output_dim --> number of nodes of the hidden layer

classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
#input_dim --> remove it as it already knows what to expect.

#the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))
#output_dim should be 1, as output is binary outcome, and activation should be 'sigmoid'
#If dependent variables have more than two categories, use activation = 'softmax'

#compile the model --> backpropagation -> gradient descent
classifier.compile(optimizer = 'adam', loss = "binary_crossentropy", metrics = ['accuracy'])
#optimizer = algorithm to find the optimal set of weights in ANN
#loss = functions that should be optimized. if more than two categories, use "categorical_crossentropy"
#metrics = criterion used to calculate the performance of the model.

WARNING: Logging before flag parsing goes to stderr.
W0901 15:08:07.067272 140494340384640 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
W0901 15:08:07.091121 140494340384640 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0901 15:08:07.094712 140494340384640 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  if sys.path[0] == '':
W0901 15:08:07.137572 140494340384640 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0901 15:08:07.158735 140494340384640 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3657: The name tf.log is deprecated. Please use tf.math.log instead.

W0901 15:08:07.166342 140494340384640 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [12]:
# Build model
classifier.fit(X_train, Y_train, batch_size = 10, nb_epoch = 20)
#batch_size = the number of observations after which you want to update the weights
#           batch size and epochs should be tuned through experiments.
#epoch = going through the whole dataset

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.
W0901 15:08:18.167969 140494340384640 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

Epoch 1/20
8000/8000 [==============================] - 1s 138us/step - loss: 0.4864 - acc: 0.7957
Epoch 2/20
8000/8000 [==============================] - 1s 107us/step - loss: 0.4271 - acc: 0.7960
Epoch 3/20
8000/8000 [==============================] - 1s 112us/step - loss: 0.4211 - acc: 0.8004
Epoch 4/20
8000/8000 [==============================] - 1s 111us/step - loss: 0.4180 - acc: 0.8246
Epoch 5/20
8000/8000 [==============================] - 1s 111us/step - loss: 0.4159 - acc: 0.8267
Epoch 6/20
8000/8000 [==============================] - 1s 111us/step - loss: 0.4142 - acc: 0.8309
Epoch 7/20
8000/8000 [==============================] - 1s 111us/step - loss: 0.4123 - acc: 0.8319
Epoch 8/20
8000/8000 [==============================] - 1s 112us/step - loss: 0.4114 - acc: 0.8331
Epoch 9/20
8000/8000 [==============================] - 1s 109us/step - loss: 0.4108 - acc: 0.8320
Epoch 10/20
8000/8000 [==============================] - 1s 110us/step - loss: 0.4093 - acc: 0.8335
Epoch 11/20
8000/8000 [==============================] - 1s 111us/step - loss: 0.4085 - acc: 0.8342
Epoch 12/20
8000/8000 [==============================] - 1s 112us/step - loss: 0.4075 - acc: 0.8335
Epoch 13/20
8000/8000 [==============================] - 1s 112us/step - loss: 0.4072 - acc: 0.8347
Epoch 14/20
8000/8000 [==============================] - 1s 111us/step - loss: 0.4069 - acc: 0.8347
Epoch 15/20
8000/8000 [==============================] - 1s 110us/step - loss: 0.4055 - acc: 0.8339
Epoch 16/20
8000/8000 [==============================] - 1s 111us/step - loss: 0.4054 - acc: 0.8360
Epoch 17/20
8000/8000 [==============================] - 1s 108us/step - loss: 0.4050 - acc: 0.8345
Epoch 18/20
8000/8000 [==============================] - 1s 108us/step - loss: 0.4046 - acc: 0.8345
Epoch 19/20
8000/8000 [==============================] - 1s 112us/step - loss: 0.4044 - acc: 0.8365
Epoch 20/20
8000/8000 [==============================] - 1s 113us/step - loss: 0.4040 - acc: 0.8347

**1.7: Optimize the model (Optional)**

**1.8: Predict the results using 0.5 as a threshold (Optional)**

In [0]:
# Evaluate model - predicting the results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #to classify each probability into True or False

**2: Print the Accuracy score and confusion matrix (5 points)**

In [14]:
#confusion matrix
cm = confusion_matrix(Y_test, y_pred)
print('Confusion matrix:')
print(cm)
#accuracy
print ('Accuracy:', (1543 + 141)/2000)

Confusion matrix:
[[1558   37]
 [ 284  121]]
Accuracy: 0.842