In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# read the data
import pandas as pd
import numpy as np
df = pd.read_csv("data.csv")
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
SALESPERSON                  30 non-null int64
Old Scheme (in thousands)    30 non-null int64
New Scheme (in thousands)    30 non-null int64
dtypes: int64(3)
memory usage: 800.0 bytes

# Q1. Find the mean of old scheme and new scheme column. (5 points)

In [2]:
# Generate descriptive statistics for the available data
des_stats = df.describe()
des_stats.reset_index(inplace = True)
des_stats.head()

   index  SALESPERSON  Old Scheme (in thousands)  New Scheme (in thousands)
0  count    30.000000                  30.000000                  30.000000
1   mean    15.500000                  68.033333                  72.033333
2    std     8.803408                  20.455980                  24.062395
3    min     1.000000                  28.000000                  32.000000
4    25%     8.250000                  54.000000                  55.000000

In [3]:
# Selecting required information
mean = des_stats.loc[1:1,['Old Scheme (in thousands)', 'New Scheme (in thousands)']]

# Answer Q1:

In [4]:
print("PFB the mean of old scheme and new scheme column:")
print(mean)

PFB the mean of old scheme and new scheme column:
   Old Scheme (in thousands)  New Scheme (in thousands)
1                  68.033333                  72.033333

# Q2. Use the five percent significance test over the data to determine the p value to check new scheme has significantly raised outputs? (10 points)
# Q3. What conclusion does the test (p-value) lead to? (2.5 points)

In [5]:
from scipy.stats import ttest_1samp, ttest_ind, mannwhitneyu, levene, shapiro, wilcoxon
from statsmodels.stats.power import ttest_power
from scipy import stats

# Separating the data into 2 groups
pre = df['Old Scheme (in thousands)']
post = df['New Scheme (in thousands)']

In [6]:
# For checking equality of variance between groups
# Null Hypothesis: Variances are equal
levene(pre,post)
print("Since p-value > 0.05, null hypothesis cannot be rejected - Variances of two groups are equal")

LeveneResult(statistic=1.063061539437244, pvalue=0.30679836081811235)

Since p-value > 0.05, null hypothesis cannot be rejected - Variances of two groups are equal

In [7]:
# For checking Normality distribution of each distribution
# Null Hypothesis: Distribution is Normal
print("Shapiro results for 'pre' group:")
shapiro(pre)
print("Shapiro results for 'post' group:")
shapiro(post)
print("Since p-value > 0.05 for both the groups, null hypothesis cannot be rejected - Distribution is normal for both groups")

Shapiro results for 'pre' group:

(0.9885101914405823, 0.9813658595085144)

Shapiro results for 'post' group:

(0.9687567353248596, 0.5057420134544373)

Since p-value > 0.05 for both the groups, null hypothesis cannot be rejected - Distribution is normal for both groups

# Answer Q2:

In [8]:
# Selecting paired t-test as we doing two measurments on the same experimental unit
# same set of 30 salesmen before and after change of incentive scheme
t_statistic, p_value = ttest_1samp(post - pre, 0)
print ("paired t-test p-value=", p_value)

paired t-test p-value= 0.13057553961337662

# Answer Q3:

In [9]:
print("Since p-value > 0.05, null hypothesis can't be rejected - The mean sales before and after change of incentive")
print("scheme hasn't raised significantly (5% significance test)")

Since p-value > 0.05, null hypothesis can't be rejected - The mean sales before and after change of incentive
scheme hasn't raised significantly (5% significance test)

# Q4.     Suppose it has been calculated that in order for Titan to break even, the average output must increase by £5000 in the scheme compared to the old scheme. If this figure is alternative hypothesis, what is: a) The probability of a type 1 error? (2.5 points) b) What is the p- value of the hypothesis test if we test for a difference of Dollars 5000? (5 points) c) Power of the test (5 points

In [10]:
# Calculating difference in output for each sales person
df['increase'] = df["New Scheme (in thousands)"] - df["Old Scheme (in thousands)"]
df.describe()
increase = df['increase']

,SALESPERSON,Old Scheme (in thousands),New Scheme (in thousands),increase
count,30.000000,30.000000,30.000000,30.000000
mean,15.500000,68.033333,72.033333,4.000000
std,8.803408,20.455980,24.062395,14.081046
min,1.000000,28.000000,32.000000,-34.000000
25%,8.250000,54.000000,55.000000,-6.750000
50%,15.500000,67.000000,74.000000,7.500000
75%,22.750000,81.500000,85.750000,16.000000
max,30.000000,110.000000,122.000000,25.000000

In [11]:
# For checking Normality distribution of distribution
# Null Hypothesis: Distribution is Normal
print("Shapiro results for 'increase':")
shapiro(increase)
print("Since p-value > 0.05 for increase, null hypothesis cannot be rejected - Distribution is normal for increase in output")

Shapiro results for 'increase':

(0.9396390914916992, 0.08894602954387665)

Since p-value > 0.05 for increase, null hypothesis cannot be rejected - Distribution is normal for increase in output

# Answer Q4, a): The probability of a type 1 error? (2.5 points)

In [12]:
print("The level of significance/alpha is set at 0.05 for the one-tailed tests below, hence the probability of a type 1 error (false rejection of null hypothesis) is 0.025 (2.5 percent)")

The level of significance/alpha is set at 0.05 for the one-tailed tests below, hence the probability of a type 1 error (false rejection of null hypothesis) is 0.025 (2.5 percent)

In [13]:
# Running one sample t-test for increase in output
# null hypothesis: average increase = 5 ('in thousands')
# alternative hypothesis: one-tailed, less than 5 ('in thousands')
m = 5
results = stats.ttest_1samp(increase, m)
alpha = 0.05
if (results[0] < 0) & (results[1]/2 < alpha):
    print("reject null hypothesis, mean is less than {}".format(m))
else:
    print("accept null hypothesis")
results

accept null hypothesis

Ttest_1sampResult(statistic=-0.3889785955886094, pvalue=0.7001334912613286)

# Answer Q4, b): What is the p- value of the hypothesis test if we test for a difference of Dollars 5000? (5 points)

In [14]:
pval = results[1]/2
print("p- value of the hypothesis test if we test for a difference of Dollars 5000: {}".format(pval))

p- value of the hypothesis test if we test for a difference of Dollars 5000: 0.3500667456306643

In [15]:
# Calculating Power of Test
# Compute the difference in Means between Population and Sample and divide it by Standard Deviation
# Set the number of Observations
# Set the alpha value and alternative values 'two-sided' , 'larger' , 'smaller'
val = (np.mean(increase) - 5) / np.std(increase)
powert = ttest_power(val, nobs=30, alpha=0.05, alternative='smaller')

# Answer Q4, c): Power of the test (5 points)

In [16]:
print("Power of the test: {}".format(powert))

Power of the test: 0.10412668718582388